name: Build for JitPack
on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Project
        run: ./gradlew build --no-daemon

      - name: Upload Main Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LavaSrc.jar
          path: main/build/libs/lavasrc-*.jar

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LavaSrc-Plugin.jar
          path: plugin/build/libs/lavasrc-plugin-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Main Artifact
        uses: actions/download-artifact@v3
        with:
          name: LavaSrc.jar

      - name: Download Plugin Artifact
        uses: actions/download-artifact@v3
        with:
          name: LavaSrc-Plugin.jar

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            main/build/libs/lavasrc-*.jar
            plugin/build/libs/lavasrc-plugin-*.jar
          allowUpdates: true
